### ISSUE TITLE
Add title and credits

### ISSUE THREAD

**Issue by Julian-O** [andrew-t/junimoji#1]
Most of the Junimoji I have seen have a title. They also all have a setter, who has both moral and legal rights to their compositions.

It is a terrific feature that a puzzle can simply be shared as a URL, but this means it is likely to be separated from this metadata about the puzzle.

Please consider adding to the URL and the display some extra optional fields consisting at least of:

* A puzzle title
* The setter's name or handle
* A description (which might be used for a copyright notice, a date, or similar).

**Comment by andrew-t** [comment]
This is a good idea. I've added a sidebar with title and author's name. We can add more details later but I'm not sure what would be sensible yet. Maybe a URL to link to the author?

**Comment by Julian-O** [comment]
Looks great
