### ISSUE TITLE
Distinguish between black squares, white squares and unknown squares.

### ISSUE THREAD

**Issue by Julian-O** [andrew-t/junimoji#2]
If I am working in one corner of the puzzle, and I enter a black square, the software helpfully fills in the corresponding blacks square that is opposite.

However, if I fill in a letter, it doesn't highlight that the corresponding opposite square must be white, must contain a letter.

I would propose that all squares be initially a light gray-colour (some with a tint to separate sub-regions.) If a cell is filled in with a letter, it should get a white background and the corresponding letter on the opposite side of the grid should also turn white.

[Another colour scheme or visual indicator may look more attractive; the current developer has a better sense of style than me. I am just trying to emphasize that the distinction between black, white and not-yet-known should be made.]

**Comment by andrew-t** [comment]
Yeah, I thought about a light-grey, but I worried it would be confusing with the checkerboard pattern. Also wasn't sure how to toggle it. What I've done is to draw a small dot in any empty cell whose mirror has a letter in it. It means you can't say "this cell definitely isn't black but I've no idea what it is" but I think that's probably OK?

**Comment by Julian-O** [comment]
That's a great solution.
